// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAZqiKg9sSPJWmCA6f150FopBMDvBicvU',
    appId: '1:70333874080:web:6cd10b784fd0a9633beec5',
    messagingSenderId: '70333874080',
    projectId: 'chef-vision-b4188',
    authDomain: 'chef-vision-b4188.firebaseapp.com',
    storageBucket: 'chef-vision-b4188.firebasestorage.app',
    measurementId: 'G-X1GF8F698W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuKIz1sDjzQ_RZ7VnXMVGi3-foD8Lz5GY',
    appId: '1:70333874080:android:d6bf132fcb4fc46f3beec5',
    messagingSenderId: '70333874080',
    projectId: 'chef-vision-b4188',
    storageBucket: 'chef-vision-b4188.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5zl6QmwxIoLqN7I57CslO4Q0AKZICZLE',
    appId: '1:70333874080:ios:d15464b981564a073beec5',
    messagingSenderId: '70333874080',
    projectId: 'chef-vision-b4188',
    storageBucket: 'chef-vision-b4188.firebasestorage.app',
    iosClientId: '70333874080-cpd3guld00f6gkdjcenj2fhiq6sukkb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chefVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5zl6QmwxIoLqN7I57CslO4Q0AKZICZLE',
    appId: '1:70333874080:ios:d15464b981564a073beec5',
    messagingSenderId: '70333874080',
    projectId: 'chef-vision-b4188',
    storageBucket: 'chef-vision-b4188.firebasestorage.app',
    iosClientId: '70333874080-cpd3guld00f6gkdjcenj2fhiq6sukkb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chefVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAZqiKg9sSPJWmCA6f150FopBMDvBicvU',
    appId: '1:70333874080:web:075308583f9b22fb3beec5',
    messagingSenderId: '70333874080',
    projectId: 'chef-vision-b4188',
    authDomain: 'chef-vision-b4188.firebaseapp.com',
    storageBucket: 'chef-vision-b4188.firebasestorage.app',
    measurementId: 'G-5SSX8WX2JS',
  );
}
